apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-configmap
  labels:
    stage: production
    name: prisma 
    app: prisma
data:
  PRISMA_CONFIG: |
    port: {{ .Values.prisma.port }}
    # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
    # managementApiSecret: my-secret
    databases:
      default:
        connector: {{ .Values.prisma.db.connector }}
        host: {{ .Values.prisma.db.host }}
        port: {{ .Values.prisma.db.port }}
        user: {{ .Values.prisma.db.user }}
        password: {{ .Values.prisma.db.password }}
        migrations: true
